create table DEVELOPER
(
ID INTEGER not null,
NAME VARCHAR(255) not null,
ROLE VARCHAR(255),
ALIAS VARCHAR(255),
PROJECT_ID INTEGER not null,
primary key(id)
);

create table PROJECT
(
ID INTEGER not null,
NAME VARCHAR(255) not null,
ACCOUNT VARCHAR(255),
primary key(id)
);

INSERT INTO DEVELOPER (ID, NAME, ROLE, ALIAS, PROJECT_ID) VALUES (1, 'Gustavo', 'Dev', 'El Taita', 1);
INSERT INTO DEVELOPER (ID, NAME, ROLE, ALIAS, PROJECT_ID) VALUES (2, 'Danilo', 'Dev', 'Todo tranqui', 1);
INSERT INTO DEVELOPER (ID, NAME, ROLE, ALIAS, PROJECT_ID) VALUES (3, 'Guillermo', 'Dev', 'Pending :(', 1);
INSERT INTO DEVELOPER (ID, NAME, ROLE, ALIAS, PROJECT_ID) VALUES (4, 'David', 'Dev', 'Lobito' , 2);
INSERT INTO DEVELOPER (ID, NAME, ROLE, ALIAS, PROJECT_ID) VALUES (5, 'David', 'TL', 'Sr Dave' , 1);

INSERT INTO PROJECT (ID, NAME, ACCOUNT) VALUES (1, 'A', 'You know');
INSERT INTO PROJECT (ID, NAME, ACCOUNT) VALUES (2, 'B', 'You know');
INSERT INTO PROJECT (ID, NAME, ACCOUNT) VALUES (3, 'C', 'Other');
INSERT INTO PROJECT (ID, NAME, ACCOUNT) VALUES (4, 'C', 'Other');
INSERT INTO PROJECT (ID, NAME, ACCOUNT) VALUES (5, 'C', 'Other');
INSERT INTO PROJECT (ID, NAME, ACCOUNT) VALUES (6, 'C', 'Other');